### ISSUE TITLE
Fork of https://github.com/arnaud-lb/MtHaml

### ISSUE THREAD

**Issue by arnaud-lb** [betasyntax/haml#1]
Hi Donovan,

This repository seems to be a rebranded fork of https://github.com/arnaud-lb/MtHaml (same code, changed names, removed the reference to Authors in the README, etc). It there any reason for this ?

**Comment by betasyntax** [comment]
I didn't anything nothing has been changed yet? I see the original authors in the License file and haven't modified anything but I was planning on it hence the fork.

**Comment by betasyntax** [comment]
Just added a disclaimer in the readme warning people to use the original. The only thing I really changed I think was the composer.json file. Should I not have done that?

**Comment by arnaud-lb** [comment]
In this case, the good practice is to click on the Fork button at https://github.com/arnaud-lb/MtHaml. This way, the fork clearly indicates its nature. Then you don't have to do anything more.

**Comment by betasyntax** [comment]
k will do great software btw works really well!
